package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*
import jetbrains.buildServer.configs.kotlin.v2018_1.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'AmazonSesPlugin_HttpsGithubComJetBrainsTeamCitySESPluginRefsHeadsMaster'
in the project with id = 'AmazonSesPlugin', and delete the patch script.
*/
create(RelativeId("AmazonSesPlugin"), GitVcsRoot({
    id("AmazonSesPlugin_HttpsGithubComJetBrainsTeamCitySESPluginRefsHeadsMaster")
    name = "https://github.com/JetBrains/TeamCity.SESPlugin#refs/heads/master"
    url = "https://github.com/JetBrains/TeamCity.SESPlugin"
    authMethod = password {
        userName = "paksv"
        password = "credentialsJSON:845babb9-cf28-4149-bc82-7fc98e52c0df"
    }
}))

