package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*
import jetbrains.buildServer.configs.kotlin.v2018_1.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'TestJavaRepo_HttpsGithubComPaksvTestJavaRepoGitRefsHeadsMaster'
in the project with id = 'TestJavaRepo', and delete the patch script.
*/
create(RelativeId("TestJavaRepo"), GitVcsRoot({
    id("TestJavaRepo_HttpsGithubComPaksvTestJavaRepoGitRefsHeadsMaster")
    name = "https://github.com/paksv/test-java-repo.git#refs/heads/master"
    url = "https://github.com/paksv/test-java-repo.git"
}))

